import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Props {
  children: React.ReactNode
}

export default function Layout({ children }: Props) {
  return (
    <ClerkProvider>
      <html lang="en">
       
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
           <div className="">
             <Header/>
           </div>
          <main className="container mx-auto">
            <div className="flex items-center justify-center ">
              <div className="mt-20">
                {children}
              </div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
